// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kyve/registry/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the registry module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// pool_list ...
	PoolList []Pool `protobuf:"bytes,2,rep,name=pool_list,json=poolList,proto3" json:"pool_list"`
	// pool_count ...
	PoolCount uint64 `protobuf:"varint,3,opt,name=pool_count,json=poolCount,proto3" json:"pool_count,omitempty"`
	// funder_list ...
	FunderList []Funder `protobuf:"bytes,4,rep,name=funder_list,json=funderList,proto3" json:"funder_list"`
	// staker_list ...
	StakerList []Staker `protobuf:"bytes,5,rep,name=staker_list,json=stakerList,proto3" json:"staker_list"`
	// delegator_list ...
	DelegatorList []Delegator `protobuf:"bytes,6,rep,name=delegator_list,json=delegatorList,proto3" json:"delegator_list"`
	// delegation_pool_data_list ...
	DelegationPoolDataList []DelegationPoolData `protobuf:"bytes,7,rep,name=delegation_pool_data_list,json=delegationPoolDataList,proto3" json:"delegation_pool_data_list"`
	// delegation_entries_list ...
	DelegationEntriesList []DelegationEntries `protobuf:"bytes,8,rep,name=delegation_entries_list,json=delegationEntriesList,proto3" json:"delegation_entries_list"`
	// proposal_list ...
	ProposalList []Proposal `protobuf:"bytes,9,rep,name=proposal_list,json=proposalList,proto3" json:"proposal_list"`
	// unbonding_staking_queue_state ...
	UnbondingStakingQueueState UnbondingStakingQueueState `protobuf:"bytes,10,opt,name=unbonding_staking_queue_state,json=unbondingStakingQueueState,proto3" json:"unbonding_staking_queue_state"`
	// unbonding_staking_queue_entries ...
	UnbondingStakingQueueEntries []UnbondingStakingQueueEntry `protobuf:"bytes,11,rep,name=unbonding_staking_queue_entries,json=unbondingStakingQueueEntries,proto3" json:"unbonding_staking_queue_entries"`
	// unbonding_staker_list ...
	UnbondingStakerList []UnbondingStaker `protobuf:"bytes,12,rep,name=unbonding_staker_list,json=unbondingStakerList,proto3" json:"unbonding_staker_list"`
	// unbonding_delegation_queue_state ...
	UnbondingDelegationQueueState UnbondingDelegationQueueState `protobuf:"bytes,13,opt,name=unbonding_delegation_queue_state,json=unbondingDelegationQueueState,proto3" json:"unbonding_delegation_queue_state"`
	// unbonding_delegation_queue_entries ...
	UnbondingDelegationQueueEntries []UnbondingDelegationQueueEntry `protobuf:"bytes,14,rep,name=unbonding_delegation_queue_entries,json=unbondingDelegationQueueEntries,proto3" json:"unbonding_delegation_queue_entries"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_99000362002b89f1, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPoolList() []Pool {
	if m != nil {
		return m.PoolList
	}
	return nil
}

func (m *GenesisState) GetPoolCount() uint64 {
	if m != nil {
		return m.PoolCount
	}
	return 0
}

func (m *GenesisState) GetFunderList() []Funder {
	if m != nil {
		return m.FunderList
	}
	return nil
}

func (m *GenesisState) GetStakerList() []Staker {
	if m != nil {
		return m.StakerList
	}
	return nil
}

func (m *GenesisState) GetDelegatorList() []Delegator {
	if m != nil {
		return m.DelegatorList
	}
	return nil
}

func (m *GenesisState) GetDelegationPoolDataList() []DelegationPoolData {
	if m != nil {
		return m.DelegationPoolDataList
	}
	return nil
}

func (m *GenesisState) GetDelegationEntriesList() []DelegationEntries {
	if m != nil {
		return m.DelegationEntriesList
	}
	return nil
}

func (m *GenesisState) GetProposalList() []Proposal {
	if m != nil {
		return m.ProposalList
	}
	return nil
}

func (m *GenesisState) GetUnbondingStakingQueueState() UnbondingStakingQueueState {
	if m != nil {
		return m.UnbondingStakingQueueState
	}
	return UnbondingStakingQueueState{}
}

func (m *GenesisState) GetUnbondingStakingQueueEntries() []UnbondingStakingQueueEntry {
	if m != nil {
		return m.UnbondingStakingQueueEntries
	}
	return nil
}

func (m *GenesisState) GetUnbondingStakerList() []UnbondingStaker {
	if m != nil {
		return m.UnbondingStakerList
	}
	return nil
}

func (m *GenesisState) GetUnbondingDelegationQueueState() UnbondingDelegationQueueState {
	if m != nil {
		return m.UnbondingDelegationQueueState
	}
	return UnbondingDelegationQueueState{}
}

func (m *GenesisState) GetUnbondingDelegationQueueEntries() []UnbondingDelegationQueueEntry {
	if m != nil {
		return m.UnbondingDelegationQueueEntries
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "kyve.registry.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("kyve/registry/v1beta1/genesis.proto", fileDescriptor_99000362002b89f1)
}

var fileDescriptor_99000362002b89f1 = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x3f, 0x6f, 0xd3, 0x40,
	0x18, 0xc6, 0x63, 0x5a, 0x42, 0xfb, 0x26, 0xe9, 0x60, 0x08, 0x84, 0x40, 0x1c, 0x2b, 0x20, 0x14,
	0x06, 0x6c, 0xa5, 0xb0, 0x21, 0x31, 0x40, 0x4a, 0x25, 0xfe, 0x09, 0x1a, 0x81, 0x04, 0x4b, 0xb8,
	0xc4, 0x57, 0xf7, 0x48, 0xea, 0x33, 0xf6, 0xb9, 0x10, 0x06, 0x16, 0x06, 0x56, 0x24, 0xbe, 0x54,
	0xc7, 0x8e, 0x4c, 0x08, 0x25, 0x5f, 0x04, 0xdd, 0x7b, 0xe7, 0x24, 0xa5, 0x71, 0x4a, 0xa7, 0xc4,
	0xe7, 0xe7, 0x79, 0x7e, 0xaf, 0x1f, 0xbf, 0x32, 0xdc, 0x18, 0x8c, 0x0e, 0xa8, 0x1b, 0x51, 0x9f,
	0xc5, 0x22, 0x1a, 0xb9, 0x07, 0xad, 0x1e, 0x15, 0xa4, 0xe5, 0xfa, 0x34, 0xa0, 0x31, 0x8b, 0x9d,
	0x30, 0xe2, 0x82, 0x9b, 0x65, 0x29, 0x72, 0x52, 0x91, 0xa3, 0x45, 0xd5, 0x4b, 0x3e, 0xf7, 0x39,
	0x2a, 0x5c, 0xf9, 0x4f, 0x89, 0xab, 0x8d, 0xc5, 0x89, 0x21, 0x89, 0xc8, 0xbe, 0x0e, 0xac, 0xde,
	0x5c, 0xac, 0x99, 0x12, 0x50, 0xd5, 0xf8, 0x09, 0x50, 0xdc, 0x56, 0x83, 0x74, 0x04, 0x11, 0xd4,
	0xbc, 0x0f, 0x79, 0x15, 0x53, 0x31, 0x6c, 0xa3, 0x59, 0xd8, 0xac, 0x39, 0x0b, 0x07, 0x73, 0x5e,
	0xa2, 0xe8, 0xe1, 0xea, 0xe1, 0xef, 0x7a, 0x6e, 0x47, 0x5b, 0xcc, 0x07, 0xb0, 0x1e, 0x72, 0x3e,
	0xec, 0x0e, 0x59, 0x2c, 0x2a, 0xe7, 0xec, 0x95, 0x66, 0x61, 0xf3, 0x5a, 0x96, 0x9f, 0xf3, 0xa1,
	0x76, 0xaf, 0x49, 0xcf, 0x33, 0x16, 0x0b, 0xb3, 0x06, 0x80, 0xfe, 0x3e, 0x4f, 0x02, 0x51, 0x59,
	0xb1, 0x8d, 0xe6, 0xea, 0x0e, 0x26, 0x3e, 0x92, 0x07, 0x66, 0x1b, 0x0a, 0xbb, 0x49, 0xe0, 0xd1,
	0x48, 0x01, 0x56, 0x11, 0x90, 0x35, 0xe0, 0x63, 0x54, 0x6a, 0x04, 0x28, 0x1f, 0x42, 0xda, 0x50,
	0x88, 0x05, 0x19, 0xa4, 0x29, 0xe7, 0x97, 0xa6, 0x74, 0x50, 0x99, 0xa6, 0x28, 0x1f, 0xa6, 0x3c,
	0x87, 0x0d, 0x8f, 0x0e, 0xa9, 0x4f, 0x04, 0xd7, 0x41, 0x79, 0x0c, 0xb2, 0x33, 0x82, 0xda, 0xa9,
	0x58, 0x67, 0x95, 0xa6, 0x6e, 0x8c, 0xfb, 0x00, 0x57, 0xf5, 0x01, 0xe3, 0x41, 0x17, 0x4b, 0xf0,
	0x88, 0x20, 0x2a, 0xf9, 0x02, 0x26, 0xdf, 0x5e, 0x9e, 0xcc, 0x78, 0x20, 0x3b, 0x6d, 0x13, 0x41,
	0x34, 0xe2, 0xb2, 0x77, 0xe2, 0x0e, 0xb2, 0x76, 0xe1, 0xca, 0x1c, 0x8b, 0x06, 0x22, 0x62, 0x34,
	0x56, 0xa4, 0x35, 0x24, 0x35, 0x4f, 0x25, 0x6d, 0x29, 0x93, 0x06, 0x95, 0xbd, 0x7f, 0x6f, 0x20,
	0xe7, 0x09, 0x94, 0xc2, 0x88, 0x87, 0x3c, 0x26, 0x7a, 0x23, 0xd6, 0x31, 0xbd, 0x9e, 0xb5, 0x11,
	0x5a, 0xab, 0x43, 0x8b, 0xa9, 0x17, 0xb3, 0xbe, 0x40, 0x2d, 0x09, 0x7a, 0x3c, 0xf0, 0x58, 0xe0,
	0x77, 0xe5, 0x6b, 0x90, 0xbf, 0x1f, 0x13, 0x9a, 0x50, 0x79, 0x25, 0x68, 0x05, 0x70, 0x5b, 0x5b,
	0x19, 0xd9, 0xaf, 0x53, 0x6f, 0x47, 0x59, 0x5f, 0x49, 0x27, 0x2e, 0xbc, 0xa6, 0x55, 0x93, 0x4c,
	0x85, 0xf9, 0x15, 0xea, 0x59, 0x6c, 0x5d, 0x5e, 0xa5, 0x80, 0x4f, 0x76, 0x26, 0xba, 0x6c, 0x6a,
	0xa4, 0xe9, 0xd7, 0x93, 0x2c, 0x05, 0xa3, 0xb1, 0xf9, 0x1e, 0xca, 0xc7, 0xf9, 0xe9, 0xea, 0x16,
	0x91, 0x7a, 0xeb, 0x7f, 0xa8, 0xd3, 0x1d, 0xbe, 0x98, 0x1c, 0x3f, 0xc6, 0x76, 0xbf, 0x19, 0x60,
	0xcf, 0x10, 0x73, 0xcb, 0x31, 0xdf, 0x70, 0x09, 0x1b, 0xbe, 0x77, 0x1a, 0x6d, 0xb6, 0x24, 0x27,
	0x4a, 0x9e, 0xbd, 0xc2, 0x45, 0x22, 0xf3, 0xbb, 0x01, 0x8d, 0x25, 0x53, 0xa4, 0x5d, 0x6f, 0xe0,
	0x53, 0x9f, 0x75, 0x8e, 0xf9, 0xba, 0xeb, 0xc9, 0x12, 0x91, 0x5c, 0xeb, 0xed, 0xc3, 0xb1, 0x65,
	0x1c, 0x8d, 0x2d, 0xe3, 0xcf, 0xd8, 0x32, 0x7e, 0x4c, 0xac, 0xdc, 0xd1, 0xc4, 0xca, 0xfd, 0x9a,
	0x58, 0xb9, 0x77, 0x77, 0x7c, 0x26, 0xf6, 0x92, 0x9e, 0xd3, 0xe7, 0xfb, 0xee, 0xd3, 0xb7, 0x6f,
	0xb6, 0x5e, 0x50, 0xf1, 0x89, 0x47, 0x03, 0xb7, 0xbf, 0x47, 0x58, 0xe0, 0x7e, 0x9e, 0x7d, 0x6f,
	0xc5, 0x28, 0xa4, 0x71, 0x2f, 0x8f, 0x5f, 0xd9, 0xbb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x07,
	0xa6, 0x31, 0xfc, 0x03, 0x06, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UnbondingDelegationQueueEntries) > 0 {
		for iNdEx := len(m.UnbondingDelegationQueueEntries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UnbondingDelegationQueueEntries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	{
		size, err := m.UnbondingDelegationQueueState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if len(m.UnbondingStakerList) > 0 {
		for iNdEx := len(m.UnbondingStakerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UnbondingStakerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.UnbondingStakingQueueEntries) > 0 {
		for iNdEx := len(m.UnbondingStakingQueueEntries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UnbondingStakingQueueEntries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	{
		size, err := m.UnbondingStakingQueueState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if len(m.ProposalList) > 0 {
		for iNdEx := len(m.ProposalList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProposalList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.DelegationEntriesList) > 0 {
		for iNdEx := len(m.DelegationEntriesList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegationEntriesList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.DelegationPoolDataList) > 0 {
		for iNdEx := len(m.DelegationPoolDataList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegationPoolDataList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.DelegatorList) > 0 {
		for iNdEx := len(m.DelegatorList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegatorList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.StakerList) > 0 {
		for iNdEx := len(m.StakerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.FunderList) > 0 {
		for iNdEx := len(m.FunderList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FunderList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.PoolCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PoolCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PoolList) > 0 {
		for iNdEx := len(m.PoolList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PoolList) > 0 {
		for _, e := range m.PoolList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PoolCount != 0 {
		n += 1 + sovGenesis(uint64(m.PoolCount))
	}
	if len(m.FunderList) > 0 {
		for _, e := range m.FunderList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakerList) > 0 {
		for _, e := range m.StakerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DelegatorList) > 0 {
		for _, e := range m.DelegatorList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DelegationPoolDataList) > 0 {
		for _, e := range m.DelegationPoolDataList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DelegationEntriesList) > 0 {
		for _, e := range m.DelegationEntriesList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ProposalList) > 0 {
		for _, e := range m.ProposalList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.UnbondingStakingQueueState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.UnbondingStakingQueueEntries) > 0 {
		for _, e := range m.UnbondingStakingQueueEntries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.UnbondingStakerList) > 0 {
		for _, e := range m.UnbondingStakerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.UnbondingDelegationQueueState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.UnbondingDelegationQueueEntries) > 0 {
		for _, e := range m.UnbondingDelegationQueueEntries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolList = append(m.PoolList, Pool{})
			if err := m.PoolList[len(m.PoolList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolCount", wireType)
			}
			m.PoolCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FunderList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FunderList = append(m.FunderList, Funder{})
			if err := m.FunderList[len(m.FunderList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakerList = append(m.StakerList, Staker{})
			if err := m.StakerList[len(m.StakerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorList = append(m.DelegatorList, Delegator{})
			if err := m.DelegatorList[len(m.DelegatorList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationPoolDataList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegationPoolDataList = append(m.DelegationPoolDataList, DelegationPoolData{})
			if err := m.DelegationPoolDataList[len(m.DelegationPoolDataList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationEntriesList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegationEntriesList = append(m.DelegationEntriesList, DelegationEntries{})
			if err := m.DelegationEntriesList[len(m.DelegationEntriesList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposalList = append(m.ProposalList, Proposal{})
			if err := m.ProposalList[len(m.ProposalList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingStakingQueueState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnbondingStakingQueueState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingStakingQueueEntries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnbondingStakingQueueEntries = append(m.UnbondingStakingQueueEntries, UnbondingStakingQueueEntry{})
			if err := m.UnbondingStakingQueueEntries[len(m.UnbondingStakingQueueEntries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingStakerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnbondingStakerList = append(m.UnbondingStakerList, UnbondingStaker{})
			if err := m.UnbondingStakerList[len(m.UnbondingStakerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingDelegationQueueState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnbondingDelegationQueueState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingDelegationQueueEntries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnbondingDelegationQueueEntries = append(m.UnbondingDelegationQueueEntries, UnbondingDelegationQueueEntry{})
			if err := m.UnbondingDelegationQueueEntries[len(m.UnbondingDelegationQueueEntries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
